### ISSUE TITLE
fieldset moet in een form staan

### ISSUE THREAD

**Issue by joostf** [Sanderoost/blok-web#3]
https://github.com/Sanderoost/blok-web/blob/4d58f3e58ab28a15a97cebff9aa49f0dd292fb00/index.html#L18

**Comment by Sanderoost** [comment]
Hele nieuwe form aangemaakt in de nieuwe versie

**Comment by Sanderoost** [comment]
Ben alleen niet zeker over de 2x legend gebruiken
