### ISSUE TITLE
Geen px gebruiken in CSS

### ISSUE THREAD

**Issue by joostf** [Sanderoost/blok-web#5]
Waar dat niet gewenst is...

**Comment by Sanderoost** [comment]
Heb nu zoveel mogelijk vervangen door % of em!

**Comment by joostf** [comment]
Kan het zijn dat je de code niet opnieuw naar github hebt gecommit?

**Comment by Sanderoost** [comment]
Ik zie het inderdaad!
volgens mij is het nu goed gegaan.

Er gaan nog wel een aantal dingetjes fout in de layout van de dropdown maar daar kom ik nog wel voor naar u toe in de les.
